name: value_listenable_test
description: "Assists in testing ValueListenable objects (ex: ValueNotifier)."
version: 0.0.2
repository: https://github.com/Flutterando/value_listenable_test

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ">=1.3.0 <2.0.0"
  flutter_test:
    sdk: flutter
  test_api: ">=0.4.3 <1.0.0"
  
 
flutter:

 