name: value_listenable_test
description: "Assists in testing ValueListenable objects (ex: ValueNotifier)."
version: 0.0.1
repository: 

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ">=1.3.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter:

 